net:
  _target_: SceneSplat

path: model/scenesplat/GaussianVLM_SceneSplat/model_best_lang-pretrain-ppv2-and-scannet-fixed-all-w-normal-late-contrastive.pth
config_path: model/scenesplat/GaussianVLM_SceneSplat/config_inference.py
freeze: True
